# Generated by Django 4.2.4 on 2023-09-09 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('mark', models.IntegerField()),
                ('question_type', models.IntegerField(choices=[(1, 'manual entry'), (2, 'single choice'), (3, 'multiple choice'), (4, 'file upload')])),
                ('created_date', models.DateField(auto_now_add=True)),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.answers')),
            ],
        ),
        migrations.CreateModel(
            name='ExamDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=100, unique=True)),
                ('exam_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.questions')),
            ],
        ),
    ]
