# Generated by Django 4.2.4 on 2023-09-09 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examdetails',
            old_name='exam_name',
            new_name='exam_type',
        ),
        migrations.RemoveField(
            model_name='examdetails',
            name='questions',
        ),
        migrations.AddField(
            model_name='questions',
            name='exam',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='administrator.examdetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='answers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.answers'),
        ),
    ]
