# Generated by Django 4.2.4 on 2023-09-09 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_rename_exam_name_examdetails_exam_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='answers',
        ),
        migrations.AlterField(
            model_name='answers',
            name='answers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.questions'),
        ),
    ]
