# Generated by Django 4.2.4 on 2023-09-09 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_remove_questions_answers_alter_answers_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.questions'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answers',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
