# Generated by Django 4.2.4 on 2023-09-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_answers_question_alter_answers_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='is_correct',
            field=models.BooleanField(null=True),
        ),
    ]
